name: Local versionning

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Bump version
      run: |
        chmod +x version.sh
        ./version.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
