name: Automatic Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Bump version
      id: bump_version
      run: |
        chmod +x version.sh
        ./version.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "v$(cat version.txt)"
        release_name: "v$(cat version.txt)"
        body: "Release for tag v$(cat version.txt)"
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
