on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Bump version
      run: |
        chmod +x version.sh
        ./version.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new branch with version
      run: |
        # Extract the new version from version.txt
        NEW_VERSION=$(cat version.txt)
        # Create a new branch with the new version
        git checkout -b "release-v$NEW_VERSION"
        # Push the new branch to the repository
        git push origin "release-v$NEW_VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
