name: Automatic Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Bump version
      id: bump_version
      run: |
        chmod +x version.sh
        ./version.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Read version
      id: read_version
      run: echo "VERSION=$(cat version.txt | tr -d '\n')" >> $GITHUB_ENV

    - name: Get modified files
      id: get_modified_files
      run: |
        MODIFIED_FILES=$(git diff --name-only HEAD~1 | tr '\n' ' ')
        echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "v${{ env.VERSION }}"
        release_name: "v${{ env.VERSION }}"
        body: |
          Automatic release for version v${{ env.VERSION }}

          ## Modified Files:
          ${{ env.MODIFIED_FILES }}
        draft: false
        prerelease: false
